/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPassRouteImport } from './routes/reset-pass'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPassRouteImport } from './routes/forgot-pass'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSplitBillRouteImport } from './routes/_app.split-bill'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppGoalsRouteImport } from './routes/_app.goals'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBudgetsRouteImport } from './routes/_app.budgets'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app.transactions.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AppTransactionsAddRouteImport } from './routes/_app.transactions.add'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminTransactionsRouteImport } from './routes/_admin.admin.transactions'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminRolesRouteImport } from './routes/_admin.admin.roles'
import { Route as AdminAdminOcrLogsRouteImport } from './routes/_admin.admin.ocr-logs'

const ResetPassRoute = ResetPassRouteImport.update({
  id: '/reset-pass',
  path: '/reset-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPassRoute = ForgotPassRouteImport.update({
  id: '/forgot-pass',
  path: '/forgot-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplitBillRoute = AppSplitBillRouteImport.update({
  id: '/split-bill',
  path: '/split-bill',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppTransactionsAddRoute = AppTransactionsAddRouteImport.update({
  id: '/transactions/add',
  path: '/transactions/add',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTransactionsRoute = AdminAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRolesRoute = AdminAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOcrLogsRoute = AdminAdminOcrLogsRouteImport.update({
  id: '/ocr-logs',
  path: '/ocr-logs',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-pass': typeof ForgotPassRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-pass': typeof ResetPassRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/budgets': typeof AppBudgetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/split-bill': typeof AppSplitBillRoute
  '/admin/ocr-logs': typeof AdminAdminOcrLogsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/transactions/add': typeof AppTransactionsAddRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-pass': typeof ForgotPassRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-pass': typeof ResetPassRoute
  '/budgets': typeof AppBudgetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/split-bill': typeof AppSplitBillRoute
  '/admin/ocr-logs': typeof AdminAdminOcrLogsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/transactions/add': typeof AppTransactionsAddRoute
  '/admin': typeof AdminAdminIndexRoute
  '/transactions': typeof AppTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/forgot-pass': typeof ForgotPassRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-pass': typeof ResetPassRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/split-bill': typeof AppSplitBillRoute
  '/_admin/admin/ocr-logs': typeof AdminAdminOcrLogsRoute
  '/_admin/admin/roles': typeof AdminAdminRolesRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/transactions': typeof AdminAdminTransactionsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_app/transactions/add': typeof AppTransactionsAddRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-pass'
    | '/login'
    | '/register'
    | '/reset-pass'
    | '/admin'
    | '/budgets'
    | '/dashboard'
    | '/goals'
    | '/reports'
    | '/settings'
    | '/split-bill'
    | '/admin/ocr-logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/transactions/add'
    | '/admin/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-pass'
    | '/login'
    | '/register'
    | '/reset-pass'
    | '/budgets'
    | '/dashboard'
    | '/goals'
    | '/reports'
    | '/settings'
    | '/split-bill'
    | '/admin/ocr-logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/transactions/add'
    | '/admin'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/forgot-pass'
    | '/login'
    | '/register'
    | '/reset-pass'
    | '/_admin/admin'
    | '/_app/budgets'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/split-bill'
    | '/_admin/admin/ocr-logs'
    | '/_admin/admin/roles'
    | '/_admin/admin/settings'
    | '/_admin/admin/transactions'
    | '/_admin/admin/users'
    | '/_app/transactions/add'
    | '/_admin/admin/'
    | '/_app/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPassRoute: typeof ForgotPassRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPassRoute: typeof ResetPassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-pass': {
      id: '/reset-pass'
      path: '/reset-pass'
      fullPath: '/reset-pass'
      preLoaderRoute: typeof ResetPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-pass': {
      id: '/forgot-pass'
      path: '/forgot-pass'
      fullPath: '/forgot-pass'
      preLoaderRoute: typeof ForgotPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/split-bill': {
      id: '/_app/split-bill'
      path: '/split-bill'
      fullPath: '/split-bill'
      preLoaderRoute: typeof AppSplitBillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_app/transactions/add': {
      id: '/_app/transactions/add'
      path: '/transactions/add'
      fullPath: '/transactions/add'
      preLoaderRoute: typeof AppTransactionsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/transactions': {
      id: '/_admin/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminAdminTransactionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ocr-logs': {
      id: '/_admin/admin/ocr-logs'
      path: '/ocr-logs'
      fullPath: '/admin/ocr-logs'
      preLoaderRoute: typeof AdminAdminOcrLogsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminOcrLogsRoute: typeof AdminAdminOcrLogsRoute
  AdminAdminRolesRoute: typeof AdminAdminRolesRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminTransactionsRoute: typeof AdminAdminTransactionsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminOcrLogsRoute: AdminAdminOcrLogsRoute,
  AdminAdminRolesRoute: AdminAdminRolesRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminTransactionsRoute: AdminAdminTransactionsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSplitBillRoute: typeof AppSplitBillRoute
  AppTransactionsAddRoute: typeof AppTransactionsAddRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetsRoute: AppBudgetsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSplitBillRoute: AppSplitBillRoute,
  AppTransactionsAddRoute: AppTransactionsAddRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPassRoute: ForgotPassRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPassRoute: ResetPassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
